!#/bin/bash 
echo " I AM AT PDF_MASK_OVER_GRAY.sh "

## DOWLOAD RELEVANT GRAY

## DOWNLOAD RELEVANT MASKS, WE MAY HAVE HUNDRED OF MASKS SO WE NEED HUNDREDS OF DIFFERENT COLOR, WE WILL PUT NUMBERS ON THE IMAGE
## AND NUMBER AND COLORS ON THE LEGEND

## SEND TO FUNCTION WHICH CAN MAKE OVERLAPPED SLICE of the HUNDREDS OF MASKS on the GRAY SLICE

##





